# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Lunch Hunch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lunch Hunch
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'ReachabilitySwift'
    pod 'Kingfisher'
    pod 'Firebase/Analytics'

end
